version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=dreamteam_crowdfunding
      - DB_PASSWORD=your_password
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=dreamteam_crowdfunding
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: